### ISSUE TITLE
ValidationError: Situation validation failed

### ISSUE THREAD

**Issue by guillett** [sgmap/mes-aides-ui#559]
Cf mail du 17 mai à 21:13.

```
ValidationError: Situation validation failed
    at MongooseError.ValidationError (/home/main/mes-aides-ui/node_modules/mongoose/lib/error/validation.js:23:11)
    at model.Document.invalidate (/home/main/mes-aides-ui/node_modules/mongoose/lib/document.js:1629:32)
    at EmbeddedDocument.invalidate (/home/main/mes-aides-ui/node_modules/mongoose/lib/types/embedded.js:224:19)
    at /home/main/mes-aides-ui/node_modules/mongoose/lib/document.js:1501:17
    at validate (/home/main/mes-aides-ui/node_modules/mongoose/lib/schematype.js:733:7)
    at /home/main/mes-aides-ui/node_modules/mongoose/lib/schematype.js:778:11
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/home/main/mes-aides-ui/node_modules/mongoose/lib/schematype.js:738:19)
    at /home/main/mes-aides-ui/node_modules/mongoose/lib/document.js:1499:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
::ffff:127.0.0.1 - - [17/May/2017:13:31:05 +0000] "POST /api/situations/ HTTP/1.0" 500 148 "https://mes-aides.gouv.fr/foyer/resultat" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
```

**Comment by MattiSG** [comment]
@guillett il faut préciser le problème. La référence à un contenu offline ne peut être que complémentaire, pas nécessaire à la compréhension.

**Comment by guillett** [comment]
Les messages d'erreurs envoyés au front sont désormais plus clairs (cf. #628) :
- soit il s'agit du message OpenFisca,
```
{
  "code": 400,
  "errors": [
    {
      "scenarios": {
        "0": {
          "test_case": {
            "foyers_fiscaux": {
              "0": {
                "declarants": "Valeur manquante"
              }
            },
            "familles": {
              "0": {
                "parents": "Valeur manquante"
              }
            },
            "menages": {
              "0": {
                "personne_de_reference": "Valeur manquante"
              }
            }
          }
        }
      }
    }
  ],
  "message": "Bad parameters in request",
  "_id": "599c2bcaa4624e3e30a0a66f"
}
```
- soit il s'agit du message de validation Mongoose
```
{
  "errors": {
    "individus.1.scolarite": {
      "message": "`college` is not a valid enum value for path `scolarite`.",
      "name": "ValidatorError",
      "properties": {
        "enumValues": [
          "Inconnue",
          "Collège",
          "Lycée"
        ],
        "type": "enum",
        "message": "`{VALUE}` is not a valid enum value for path `{PATH}`.",
        "path": "scolarite",
        "value": "college"
      },
      "kind": "enum",
      "path": "scolarite",
      "value": "college"
    }
  },
  "message": "Situation validation failed",
  "name": "ValidationError"
}
```
